### ISSUE TITLE
Lock down Ruby's ABI when packaging new gem

### ISSUE THREAD

**Issue by luislavena** [luislavena/gem-compiler#11]
The compiled extensions are bind to the specific version of Ruby used.

At this time, `required_ruby_version` in the gem specification is not updated, which should be to avoid installation of incorrect binaries on different versions.

Perhaps we should use `RbConfig::CONFIG["ruby_version"]` as ABI indicator:

```
$ ruby -rrbconfig -ve 'p RbConfig::CONFIG["ruby_version"]'
ruby 1.8.7 (2013-06-27 patchlevel 374) [i686-darwin14.0.0]
"1.8"

$ ruby -rrbconfig -ve 'p RbConfig::CONFIG["ruby_version"]'
ruby 1.9.3p551 (2014-11-13) [x86_64-darwin14.0.0]
"1.9.1"

$ ruby -rrbconfig -ve 'p RbConfig::CONFIG["ruby_version"]'
ruby 2.0.0p598 (2014-11-13) [x86_64-darwin14.0.0]
"2.0.0"

$ ruby -rrbconfig -ve 'p RbConfig::CONFIG["ruby_version"]'
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]
"2.1.0"
```

**Comment by mpapis** [comment]
how about this:
```bash
# rvm 1.8.7,jruby,rbx,2.2 --fuzzy do ruby -rrubygems -ve 'puts [Gem.ruby_engine,RUBY_VERSION]'
ruby 1.8.7 (2013-06-27 patchlevel 374) [x86_64-linux]
ruby
1.8.7
jruby 1.7.18 (1.9.3p551) 2014-12-22 625381c on OpenJDK 64-Bit Server VM 1.8.0_40-b10 +jit [linux-amd64]
jruby
1.9.3
rubinius 1.3.3 (1.8.7 d3b59ba3 2014-06-22 JI) [x86_64-linux-gnu]
rbx
1.8.7
ruby 2.2.0preview1 (2014-09-17 trunk 47616) [x86_64-linux]
ruby
2.2.0
```

**Comment by luislavena** [comment]
@mpapis not sure to understand your comment.

`Gem.ruby_engine` is nothing that RubyGems can detect during search of dependency of the gem, unless `ruby_engine` is something that shows as part of the platform.

Please note that `gem-compiler` compiles things defined as extensions (using RubyGems' mechanisms) and then packages a binary/native gem of it.

Since platform is already part of the gem specification, the idea to lock `required_ruby_platform` is to be able to avoid a binary gem compiled with Ruby 2.1.x to be installed by mistake on a 2.2.x or 1.9.x installation.

Of course RubyGems server has no idea of differentiate same gem version and platform for different Ruby versions, but I personally don't care about that.

Does that make sense?

**Comment by mpapis** [comment]
ah right, there will be java platform but support for cext on jruby is experimental - so no difference there, as for rubinius it's supposed to be fully compatible so possibly it could work between mri and rbx - sorry for confusing things

as for versions compatibility ruby 2.1+ only two first digits count

**Comment by luislavena** [comment]
> as for versions compatibility ruby 2.1+ only two first digits count

No need:

```ruby
versions = %w(1.9.3 2.1.0 2.1.2 2.1.5 2.2.0 2.2.1).map { |v| Gem::Version.new(v) }
#=> [#<Gem::Version "1.9.3">, #<Gem::Version "2.1.0">, #<Gem::Version "2.1.2">, #<Gem::Version "2.1.5">, #<Gem::Version "2.2.0">, #<Gem::Version "2.2.1">]

req = Gem::Requirement.new "~> 2.1.0"
#=> #<Gem::Requirement:0x007f8c62893a00 @requirements=[["~>", #<Gem::Version "2.1.0">]]>

versions.collect { |v| [v.to_s, req.satisfied_by?(v)] }
# [["1.9.3", false],
# ["2.1.0", true],
# ["2.1.2", true],
# ["2.1.5", true],
# ["2.2.0", false],
# ["2.2.1", false]]
```

Gems packages using `~>` and `RbConfig::CONFIG["ruby_version"]` will only be able to be installed under those versions.
