### ISSUE TITLE
Use only in gemfile?

### ISSUE THREAD

**Issue by fxfactorial** [luislavena/gem-compiler#25]
Somewhat similar to https://github.com/luislavena/gem-compiler/issues/8 but here is my case: 

I have a unique process that will collect all needed gems and distribute them as a single application to windows. I do this on OS X. 

So I have successfully created `unf_ext-0.0.7.4-x86-mingw32.gem` on windows, moved that to my project, and added this to the Gemfile

```
gem 'unf_ext', :path => './'
```

but when I try to work my rake tasks on OS X, I get 

```
rake package                                                                                                                                               ⏎
Could not find gem 'unf_ext' in source at `./`.
Source does not contain any versions of 'unf_ext'
Run `bundle install` to install missing gems.
```

Which I guess is because the binary formats are different, but there must be a way to get around this because it shouldn't matter, we're just moving it around, not running it.

**Comment by luislavena** [comment]
Hello @fxfactorial and thank you for your questions.

When you say:

> So I have successfully created `unf_ext-0.0.7.4-x86-mingw32.gem` on windows, moved that to my project

Please note that the generated binary is **bound** to Windows platform. Attempt to be use or install on another platform will not work.

Perhaps you might want to use [`bundle package`](http://bundler.io/v1.2/bundle_package.html) instead.

In theory you can place multiple platform gems within `vendor/cache` and let `bundle install --local` automatically detect them.

You might need to store both ruby (non-platform specific) and platform specific gems in the cache.

> Which I guess is because the binary formats are different, but there must be a way to get around this because it shouldn't matter, we're just moving it around, not running it.

Actually, it _**does**_ matter. A gem for a different platform might no be found on a different one. Also if you're using Bundler lockfiles, it might contain some locked dependencies that are platform-specific and those cannot be installed under a different OS.

---

On a separate note, I see `unf_ext` already provides binaries for different platforms, so I'm not sure the role of gem-compiler on your question.

Hope that helps. Closing this now.

If you have an specific question related to gem-compiler itself, please feel free to open a new issue.

Cheers.

**Comment by luislavena** [comment]
Hello @fxfactorial I just realized from your sample:

```ruby
gem 'unf_ext', :path => './'
```

The `:path` option indicates Bundler to look for `unf_ext` **source** in the given directory, not a packaged gem file.

Please see my response in #26 and reach out to Bundler for further assistance with it's usage.

Cheers.
