### ISSUE TITLE
Testing with trunk ruby 2.5.0dev (2017-10-10 trunk 60155) [x64-mingw32]

### ISSUE THREAD

**Issue by MSP-Greg** [luislavena/gem-compiler#30]
Luis,

Just forked this, and added trunk to Appveyor.  Had two failures that looked version related.
<https://ci.appveyor.com/project/MSP-Greg/gem-compiler/build/job/62q08u00mycg9j9o>

Hope things are well...

**Comment by luislavena** [comment]
Hello @MSP-Greg, thank you for your report!

I've created #31 to solve this, can you run your tests against that branch?

Thank you.

PS: Not sure if RubyInstaller provides an _official_ trunk artifact, but that will be great to add to AppVeyor matrix (like `ruby-head` on Travis) 😉

**Comment by MSP-Greg** [comment]
Thanks for the quick fix.  That passed, [AV test](https://ci.appveyor.com/project/MSP-Greg/gem-compiler/build/job/k5o38ogjdff8d17e).

Re trunk & 'official', you may recall that I've been building MSYS2/MinGW trunk for quite a while (before RI2), and I was always concentrated on repeatable testing.  RI2 / Lars was focused on the runtime and 2.4.

Using it is your choice.  [ruby/spec](https://github.com/ruby/spec/blob/master/appveyor.yml) and [rubygems/rubygems](https://github.com/rubygems/rubygems/blob/master/appveyor.yml) are using it, and more soon.  I'ts a rolling build done twice a day, I may cancel a build if there's only a real commit or two (ignoring svn commits).  Some history [here](https://msp-greg.github.io/file.mingw_test-all.html).

Previously, I built locally and pushed to BinTray.  As noted, now it's built on AV and saved as an artifact.  Includes RI2 runtime files.

**Comment by luislavena** [comment]
Thanks @MSP-Greg, I honestly don't remember a lot of RubyInstaller 😄 

re: `trunk` builds, interesting seeing adoption and thanks for the links, will consider adding that to this gem build process.

Once again, thank you for your report and your contributions to Ruby on Windows!
❤️ ❤️ ❤️
