### ISSUE TITLE
Compiler errors when it finds nothing to do?

### ISSUE THREAD

**Issue by bimargulies** [luislavena/gem-compiler#38]
I tried to set up a loop compiling all the dependencies of the thing I was working on.

+ gem compile addressable-2.5.2.gem
ERROR:  While executing gem ... (Gem::Compiler::CompilerError)
    There are no extensions to build on this gem file.
Unpacking gem: 'addressable-2.5.2' in temporary directory...

**Comment by luislavena** [comment]
Hello @bimargulies and welcome!

gem-compiler will try to compile the gem, when supplied with a gem that has no extensions, it fail with the above error (it will also fail if the supplied gem is one already compiled.

Do you suggest that instead a noop (no operation) note be displayed instead of an error?

Cheers.

**Comment by bimargulies** [comment]
How about distinct exit statuses:

0 for compiled and wrote output
1 for nothing wrong and nothing to do
2 for something actually went wrong

?

**Comment by luislavena** [comment]
Hello, apologies for the delay getting back to you.

Not sure that I follow your suggestion.

From what I understood from your original report was that compiling (in a loop) triggers and error when there is nothing to compile, which I assume is a problem.

But your current suggestion still suggest return an error.

I'm not precisely sure that we can control the exit code of an specific exception triggered, except doing an unclean `exit` in the code.

Is that what you're suggesting?

**Comment by luislavena** [comment]
Hello @bimargulies, just merged a change to this. See #47 for details.

Cheers.
