### ISSUE TITLE
Compile targeting a different platform of Ruby (cross-compilation)

### ISSUE THREAD

**Issue by luislavena** [luislavena/gem-compiler#4]
In order to produce binaries for another platform, I should be able to indicate the platform so cross-compilation could happen.

### Add cross-compiled Ruby to the list of interpreters

Using `interpreters` command, user should be able to add Ruby interpreters for platforms other than the current one.

### Compile to a different platform

    $ gem compile GEMFILE --platform=x86-mingw32

Specify the platform (which is mentioned in the list of interpreters) to target the compilation.

If no `--ruby` or `--abi` is provided, it will assume the current Ruby version but targeting the specified platform.

If such version is not found, it should trigger an error.

### Compile to different platform and version

    $ gem compile GEMFILE --ruby=1.8.7 --platform=x86-mingw32

Combining both `--platfrom` and `--ruby` (or `--abi`) provides the maximum flexibility when current Ruby version is not the same you are targeting.

When used, the Ruby version, patchlevel, platform and ABI will be displayed:

    Unpacking gem: 'yajl-ruby-1.1.0' in temporary directory...
    Using Ruby 1.8.7-p358 (1.8) (x86-mingw32, non-native)...
    Building native extensions.  This could take a while...

An additional `non-native` legend is displayed, indicating that *using* is actually attempting to mimic the target configuration.

### Notes about cross-compilation

Under some circumstances, certain versions of Ruby cannot be cross-compiled when the current Ruby is greater than the target.

For example, it fails to cross-compile to Ruby 1.8.7 when current Ruby version is 1.9.3. However, cross-compile to 1.9.3 from 1.8.7 is possible.

This is a Ruby limitation that you need to keep in mind when using this functionality.

**Comment by simplytech** [comment]
Hello! I'm very interested in this feature and I would like to help to achieve it. Could you please point me to which file(s) I can start looking at?

**Comment by luislavena** [comment]
Hello @simplytech and thank you for your interest!

The complexity around this issue is a bit high, as I believe it requires #2 and #3 to be implemented first in order to achieve that.

I created gem-compiler out of issues attempting to get [rake-compiler](https://github.com/rake-compiler/rake-compiler) adopted by some projects.

Right now rake-compiler does provide cross-compilation, but it requires modification of how gems are built.

There is no specific place in gem-compiler to look for cross-platform support, but should be in the lines of hi-jacking `ExtBuilder` and ensure the `RbConfig` information of the target platform is set in place (plus the `fake.rb` file required to change the platform).

It also requires the target Ruby be present, which means you need to cross-compile Ruby for the desired platform and refer to it.

While rake-compiler code might be a bit too much, the principle described above is the same: have the target Ruby installed, know where its `rbconfig.rb` is and use it to deceive your native Ruby to compile the extension for that platform.

I'm no longer pursuing this *feature* due it's complexity, but feel free to explore the ideas and ask questions about it.

Cheers!
