### ISSUE TITLE
modify the version of the gem

### ISSUE THREAD

**Issue by micheelengronne** [luislavena/gem-compiler#57]
Is it possible to alter the version of the fat gem ?

I would like to use a version like that: `1.0.0.20200525` for the fat gem when the gem is itself `1.0.0`.

Why ?

Because if there is a problem with the fat gem after being uploaded in a local gemstash, there is no way to push a new one with the same version and we are dependant of the creation of a new version in the upstream gem.

**Comment by luislavena** [comment]
Hello @micheelengronne, thanks for your patience and your question.

There is no option to alter the gem version, and I would personally prefer to avoid that, as the new packaged version will not be the same as upstream, which can introduce version comparison issues.

You can test the gem by installing it locally before pushing to a gem server.

While I do understand the reason, I'm not convinced is the best approach.

Let me know if you have further questions.

Cheers.

**Comment by micheelengronne** [comment]
Of course we test a gem locally before pushing to a gem server. but in case of mistakes like a false-negative test, we are screwed.

As stated here https://github.com/rubygems/gemstash/issues/266#event-3380099239 it is advised to always publish a new version by using a 4th or 5th number in the version. That should avoid versions conflicts with the upstream and make mistakes less harmful.

**Comment by micheelengronne** [comment]
I created this PR to answer to my question: https://github.com/luislavena/gem-compiler/pull/59

**Comment by micheelengronne** [comment]
I coded it as an option. That way, if someone fear a potential conflict with the upstream gem version, they can not use it.

I would be very happy to see it merged as I have differents builds of a same gem in my CI waiting to be pushed in my Gemstash.

**Comment by luislavena** [comment]
Hello @micheelengronne 

Thank you for your patience. I was not able to look at this in more detail before.

I appreciate your effort in the PR and your desire of getting that incorporated. While I understand the scenario you present is valid (now that I fully understand it), I'm not aligned on the UX presented in your PR.

If you don't mind, I have a few changes pending for this project that I would like to close before I tackle this particular request.

Hopefully will have an update shortly.

Once again, thank you for your patience and your contribution.

Cheers.

**Comment by micheelengronne** [comment]
No problem.

I am happy that you found my contribution useful.
