### ISSUE TITLE
Thanks!!!

### ISSUE THREAD

**Issue by gsinclair** [luislavena/gem-compiler#62]
No issues, just wanted to say thanks for this incredibly useful piece of work. When I was struggling to install prawn on a non-techy colleague's computer because it now relies on a compiled racc, I discovered gem-compiler and it worked for me first time, exactly as set out in the readme. I am very grateful.

Now I've created extra work for you in having to file this non-issue, so sorry about that, but you deserve to know how helpful the software has been.

**Comment by luislavena** [comment]
Thank you @gsinclair for your kind words! I'm happy to hear that docs and functionality were straight forward! 😊 

While this is a non-issue, is really satisfying hear that one of my contributions was able to help others the same way that helped me, that to me embodies the whole reason Open-Source is all about.

Thank you again for taking the time and submitting this ❤️ ❤️ ❤️ 
Cheers.
